/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    FundingRecipient: {
      address: "0xb19b36b1456e65e3a6d514d3f715f204bd59f431",
      abi: [
        {
          type: "function",
          name: "complete",
          inputs: [],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "completed",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 4,
    },
    CrowdFund: {
      address: "0x8ce361602b935680e8dec218b820ff5056beb7af",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "fundingRecipientAddress",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "receive",
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "contribute",
          inputs: [],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "contributions",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "deadline",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "execute",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "fundingRecipient",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract FundingRecipient",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "goal",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "timeLeft",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "totalContributions",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "withdraw",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "Contributed",
          inputs: [
            {
              name: "contributor",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Executed",
          inputs: [
            {
              name: "totalAmount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Withdrawn",
          inputs: [
            {
              name: "contributor",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "CrowdFund__AlreadyCompleted",
          inputs: [],
        },
        {
          type: "error",
          name: "CrowdFund__DeadlineNotReached",
          inputs: [],
        },
        {
          type: "error",
          name: "CrowdFund__ExecuteFailed",
          inputs: [],
        },
        {
          type: "error",
          name: "CrowdFund__GoalAlreadyReached",
          inputs: [],
        },
        {
          type: "error",
          name: "CrowdFund__GoalNotReached",
          inputs: [],
        },
        {
          type: "error",
          name: "CrowdFund__NoContribution",
          inputs: [],
        },
        {
          type: "error",
          name: "CrowdFund__WithdrawFailed",
          inputs: [],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 5,
    },
  },
  11155111: {
    FundingRecipient: {
      address: "0x9c8e5891c9ce52eabaaa8ff5f760e292f553ee79",
      abi: [
        {
          type: "function",
          name: "complete",
          inputs: [],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "completed",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 11228139,
    },
    CrowdFund: {
      address: "0xe3ed421739ce651084e3ab51a7571d900c4baa16",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "fundingRecipientAddress",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "receive",
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "contribute",
          inputs: [],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "contributions",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "deadline",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "execute",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "fundingRecipient",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "contract FundingRecipient",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "goal",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "timeLeft",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "totalContributions",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "withdraw",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "Contributed",
          inputs: [
            {
              name: "contributor",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Executed",
          inputs: [
            {
              name: "totalAmount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Withdrawn",
          inputs: [
            {
              name: "contributor",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "CrowdFund__AlreadyCompleted",
          inputs: [],
        },
        {
          type: "error",
          name: "CrowdFund__DeadlineNotReached",
          inputs: [],
        },
        {
          type: "error",
          name: "CrowdFund__ExecuteFailed",
          inputs: [],
        },
        {
          type: "error",
          name: "CrowdFund__GoalAlreadyReached",
          inputs: [],
        },
        {
          type: "error",
          name: "CrowdFund__GoalNotReached",
          inputs: [],
        },
        {
          type: "error",
          name: "CrowdFund__NoContribution",
          inputs: [],
        },
        {
          type: "error",
          name: "CrowdFund__WithdrawFailed",
          inputs: [],
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 11228139,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
